### ISSUE TITLE
мониторинг активности с дэшбордом

### ISSUE THREAD

**Issue by mixx3** [profcomff/marketing-backend#8]
https://habr.com/ru/post/431754/
GET ручка с авторизацией -> HTMLResponse таблички, сгенерированной с помощью Dash
(мб как параметр задавать, что надо нарисовать: DAU, WAU, MAU, ещё что то =])

**Comment by dyakovri** [comment]
Ручка через mount делается в Dash

```python
app = dash.Dash(__name__, requests_pathname_prefix="/dashboard/")
# ...
server.mount("/dashboard", WSGIMiddleware(app.server))
```
Пример: https://gist.github.com/dmontagu/b89821fc64101f2143ddc256103eca59

**Comment by dyakovri** [comment]
DAU, WAU, MAU, Retention я бы показывал всегда, это основные параметры

---

> DAU - количество уникальных посетителей в день, WAU - за последние 7 дней, MAU - за последние 30 дней. 
> 
> Retention – гистограмма количества пользователей, которые вернулись со дня регистрации, от дней с момента регистрации. Как считать: селектишь days(max(action ts)-min(action  ts)) для каждого marketing id, потом считаешь количество marketing id для каждого количества дней. Результат можно отдать массивом 
>
